name: Build and Archive (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir build

      - name: Configure project with CMake (Release)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release

      - name: Install binary to ./bin
        run: cmake --install build --config Release --prefix ./bin

      - name: List installed files
        run: dir bin\bin

      - name: Create ZIP archive
        run: |
          mkdir artifacts
          powershell Compress-Archive -Path bin\bin\systemy-operacyjne.exe -DestinationPath artifacts\systemy-operacyjne-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: systemy-operacyjne-windows
          path: artifacts/systemy-operacyjne-windows.zip
